### PR TITLE
Fix null ref exception: add default constructor to initialise bezierpath instance

### LINKED ISSUE #130: Getting constant NullReferenceException s in Unity 2022.2.10
I've tried to add this to my project in Unity 2022.2.10 but as soon as I add the 'Path Creator' component to a blank object, the console gets flooded with errors and I don't see any of the expected path visuals/objects/gizmos.

I'm not smart enough to debug this, is it just not compatible with this version of Unity?

image

### PR DESCRIPTION
**Pull request by riccardone**
this is to make the package work in version 22.> and avoid null ref exception error

Closes #130

### CODE REVIEW

**Review by ZakAuMiel — APPROVED** [review]

**Review by krilek — APPROVED** [review]

**Review by jakesee — APPROVED** [review]
I can confirm this fixes the issue in 2022.3.7.f1:

`: Object reference not set to an instance of an object
PathCreation.BezierPath.CalculateBoundsWithTransform (UnityEngine.Transform transform) (at Assets/PathCreator/Core/Runtime/Objects/BezierPath.cs:496)
`

**Comment by scriptcoded** [comment]
@SebLague there are some good pull requests waiting for review/being merged. Do you have plans to ever maintain this great library, or would you consider handing it over to the community?

**Comment by SimonDarksideJ** [comment]
Confirmed on 2022.3.16f1, this works as described!

**Comment by ZakAuMiel** [comment]
Confirmed on 202.3.22

**Pull request merged**
