### PR TITLE
Path Generation, Sprite Shape, some handy functions

### PR DESCRIPTION
**Pull request by hadiDanial**
I've added some new features and a few handy functions. Here's a list:

**PathGenerator.cs**
Generates a 2D path over time, and creates a sprite shape that matches it, as well as a collider. 

**PathGenerator_Road.cs**
Same as above, except it generates a road mesh using Sebastian's road mesh creator.

**PathToSpriteShape.cs:**
A static class used as a tool to create a Sprite Shape spline from a path. To use sprite shapes, add the 2D SpriteShape package from the Package Manager. 
Use the `int UpdateSpriteShape(SpriteShapeController controller, PathCreator pathCreator, int j)` function.  _Pretty accurate for open paths. Tangents of the last point aren't correct on closed paths though, and have to be adjusted manually at the moment._

**PathCollider.cs**
A simple script to create an edge collider from a path and set a PhysicsMaterial2D to it.

**Functions added in VertexPath.cs:**
`float CalculatePercentByPosition(Vector3 position)` - calculates a rough path percentage/time based on the distance to the path.
`int GetNearestVertex(Vector3 position) `- Returns the index of the nearest vertex to a given position.
`Vector3 GetNearestVertexPosition(Vector3 position)` Returns the position of the nearest vertex.
`Vector3 GetDirection(int index, EndOfPathInstruction endOfPathInstruction = EndOfPathInstruction.Loop)` - returns direction from index, from the tangents array.
`Vector3[] anchorTangents` array, has tangent data for the anchor points of the bezier path.
`float GetUniformSpeed(float speed) `- returns speed as a percentage of the length of the path, allowing objects of paths that have different lengths to travel at the same speed.

**Additions to VertexPathUtility.cs**
Added `List<Vector3> anchorTangents` in `PathSplitData `. It saves the tangent vectors of the anchor points.

**Changes in BezierPath.cs:**
Made `points `list public.

I've also added a few test scenes and test scripts.

uniform speed

Objects moving at the same speed on different paths, with sprite shapes generated along the paths

### CODE REVIEW

**Comment by SebLague** [comment]
Hi, thanks for contributing. I can't review some of this at the moment though due to the use of Odin Inspector (which I don't own and don't want as a dependency for this tool). The SpriteShapeController script also appears to be missing.

**Comment by hadiDanial** [comment]
Heya! No worries. 

The use of Odin is only in a test script (ConvertToSpriteShape) to call a method from the editor, so it can be ignored if needed, or I can try to create a normal editor or remove it. You can use the static PathToSpriteShape class without it.  

The Sprite Shape Controller is from the 2D Sprite Shape package from Unity. What I've done is create a way to convert between your paths and Sprite Shape splines, so that you can use the sprite shape system, which isn't as robust when it comes to using in real time scripts IMO.

In any case, thank you for this package! I'm working on recreating a game jam game I did last year using it at the moment, and it's going great!

**Comment by hadiDanial** [comment]
> Hi, thanks for contributing. I can't review some of this at the moment though due to the use of Odin Inspector (which I don't own and don't want as a dependency for this tool). The SpriteShapeController script also appears to be missing.


I have removed the file that uses Odin from the repo. I don't know if you'd want the sprite shape stuff as it does use an external package, but I thought it'd be a nice thing to have. Maybe an add-on? 
If you have some time, could you look at what I've added in the core classes and see if there's anything I could have done better? Or if there's anything else you need/want me to try and implement. I'm still not as familiar with it as I'd like, and I'm adding things that could be useful or that I think I'll need for my project. Thanks!

**Comment by SebLague** [comment]
Great idea with the GetNearestVertex methods. I've changed the implementation a little because I think its more useful to get the actual nearest point on the path, rather than nearest vertex. The sprite stuff is cool, I will have to think about how to incorporate that at some point without requiring the sprite package.

**Comment by hadiDanial** [comment]
I'll close this for now and separate the path generation script from the sprite shape/road mesh stuff so it can be used alone if you want to include it in the examples.

> I've changed the implementation a little because I think its more useful to get the actual nearest point on the path, rather than nearest vertex. 

Yeah. that's true! Good idea

> The sprite stuff is cool, I will have to think about how to incorporate that at some point without requiring the sprite package.

I'll separate it from the rest of this and put it (and any other external package support I might add) into a different branch, so that my master will not require dependencies. Is it ok if I make other pull requests in the future?

**Comment by SebLague** [comment]
Pull requests are very welcome, thanks :)

**Pull request closed without merging**
